version: "3.9"
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: spooky-list__web-dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
  web-prod:
    container_name: spooky-list__web-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
