name: Check Lint
run-name: Running lint on PR
on: [pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm i
      - run: npm run lint